### ISSUE TITLE
Update for Bukkit / Spigot 1.8!

### ISSUE THREAD

**Issue by HeroCC** [cambeaney/HerochatBungeeBridge-Bukkit#1]
I use HeroChat and bungee, and want to link them, but it doesn't work on 1.8. Any chance you could update? Thanks!

**Comment by cambeaney** [comment]
Are you using the download from here? http://www.spigotmc.org/resources/herochatbungeebridge-bungee.189/

It works fine for me (unless I did something wrong)

**Comment by HeroCC** [comment]
My mistake, I was having some troubles with it and seeing a bunch of errors, but it turns out it was my fault. Thanks!
